version: '3.8'

services:
  web:
    build: .
    container_name: yii2_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf  # Копируем конфигурацию Nginx
    depends_on:
      - db
    networks:
      - yii2-network

  db:
    image: mysql:8.0
    container_name: yii2_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: yii2db
      MYSQL_USER: yii2user
      MYSQL_PASSWORD: yii2password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - yii2-network

volumes:
  dbdata:

networks:
  yii2-network:
    driver: bridge
